global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/varz'
    scrape_interval: 30s

  - job_name: 'ledgerflux-services'
    static_configs:
      - targets: ['gateway:8000', 'ingestor:8080', 'normalizer:8081', 'snapshotter:8082']
    scrape_interval: 30s
