apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
  namespace: ledgerflux
  labels:
    app: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb
        image: amazon/dynamodb-local:2.0.0
        ports:
        - containerPort: 8000
          name: dynamodb
        command:
        - java
        - -jar
        - DynamoDBLocal.jar
        - -sharedDb
        - -inMemory
        - -port
        - "8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  namespace: ledgerflux
  labels:
    app: dynamodb
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: dynamodb
  selector:
    app: dynamodb
