apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ledgerflux
  labels:
    app: gateway
    component: ledgerflux
spec:
  replicas: 2  # For high availability
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        component: ledgerflux
    spec:
      containers:
      - name: gateway
        image: ledgerflux-gateway:latest
        imagePullPolicy: Never  # For local development
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: LOG_LEVEL
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: PG_HOST
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: PG_PORT
        - name: PG_USER
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: PG_USER
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: PG_DATABASE
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ledgerflux-postgres
              key: PG_PASSWORD
        volumeMounts:
        - name: nats-config
          mountPath: /app/services/common/nats.config.json
          subPath: nats.config.json
        - name: gateway-config
          mountPath: /app/services/gateway/config.json
          subPath: config.json
        ports:
        - containerPort: 8000
          name: websocket
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nats-config
        configMap:
          name: ledgerflux-nats-config
          items:
          - key: nats.config.json
            path: nats.config.json
      - name: gateway-config
        configMap:
          name: ledgerflux-gateway-config
          items:
          - key: config.json
            path: config.json

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ledgerflux
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: websocket
  selector:
    app: gateway
