apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ledgerflux
  labels:
    app: gateway
    component: ledgerflux
spec:
  replicas: 2  # For high availability
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        component: ledgerflux
    spec:
      containers:
      - name: gateway
        image: ledgerflux-gateway:latest
        imagePullPolicy: Never  # For local development
        args:
        - --nats-urls
        - "nats://nats:4222"
        - --input-stream
        - "market.normalized"
        - --num-shards
        - "4"
        - --port
        - "8000"
        - --max-msgs-per-sec
        - "100"
        - --burst
        - "200"
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: LOG_LEVEL
        - name: NATS_URLS
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: NATS_URLS
        ports:
        - containerPort: 8000
          name: websocket
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ledgerflux
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: websocket
  selector:
    app: gateway
