apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: normalizer
  namespace: ledgerflux
  labels:
    app: normalizer
    component: ledgerflux
spec:
  serviceName: normalizer
  replicas: 4
  selector:
    matchLabels:
      app: normalizer
  template:
    metadata:
      labels:
        app: normalizer
        component: ledgerflux
    spec:
      containers:
      - name: normalizer
        image: ledgerflux-normalizer:simple
        imagePullPolicy: Never  # For local development
        args:
        - --nats-urls
        - "nats://nats:4222"
        - --input-stream
        - "market_ticks"
        - --output-stream
        - "market_normalized"
        - --num-shards
        - "4"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: LOG_LEVEL
        - name: NATS_URLS
          valueFrom:
            configMapKeyRef:
              name: ledgerflux-config
              key: NATS_URLS
        ports:
        - containerPort: 8081
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: normalizer
  namespace: ledgerflux
  labels:
    app: normalizer
    component: ledgerflux
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    name: metrics
  selector:
    app: normalizer
